name: Deploy via SCP

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # Zobrazíme, jaké soubory jsou dostupné v pracovním adresáři
      - name: Zkontroluj obsah repozitáře
        run: ls -la

      # Pokud soubory jsou v podsložce, změníme zdrojovou cestu v SCP
      - name: Upload files to SFTP via SCP
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass
          
          sshpass -p "${{ secrets.FTP_PASS }}" \
            scp -P 22 -o StrictHostKeyChecking=no -r * \
            ${{ secrets.FTP_USER }}@${{ secrets.FTP_HOST }}:/upload/luke-styly-kody
