name: Deploy via SFTP

on:
  push:
    branches: [ "main" ]
    # => spuštění na každý push do větve "main"

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Upload via SFTP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.FTP_HOST }}
          port: 22
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}


          source: ".*"  # Třeba vše z kořene (pozor na skryté soubory)

          target: "upload/luke-styly-kody"
