- name: Deploy via scp
  run: |
    sudo apt-get update
    sudo apt-get install -y sshpass

    # Přenést všechny soubory ze složky "dist" na SFTP
    sshpass -p "${{ secrets.SFTP_PASS }}" \
      scp -P 22 -o StrictHostKeyChecking=no -r dist/* \
      ${{ secrets.SFTP_USER }}@${{ secrets.SFTP_HOST }}:/upload/luke-styly-kody
