name: Deploy via SFTP

on:
  push:
    branches: [ "main" ]

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # KROK 1: Hned po připojení zjistíme, kde se nacházíme (pwd)
      - name: Check remote directory
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.FTP_HOST }}
          port: 22
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          script: |
            pwd
            ls -la

      # KROK 2: Nahrání souborů přes SFTP (SCP)
      - name: Upload via SFTP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.FTP_HOST }}
          port: 22
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          source: "./*"
          target: "/upload/luke-styly-kody"
